pipeline {
    agent any

    stages {
        stage('Start') {
            steps {
                script {
                    echo 'Начало работы скриптов.'
                }
            }
        }

    stages {
        stage('Установка зависимостей.') {
            steps {
                script {
                    // Активация виртуального окружения
                    sh 'python3 -m venv venv'
                    sh 'venv/Scripts/activate'

                    // Установка зависимостей из файла requirements.txt
                    sn 'pip install -r lab2/requirements.txt'
                }
            }
        }

        stage('Генерация данных.') {
            steps {
                script {
                    sh 'python3 lab2/src/data_creation.py'
                }
            }
        }

        stage('Предобработка данных.') {
            steps {
                script {
                    sh 'python3 lab2/src/model_preparation.py'
                }
            }
        }

        stage('Обучение модели.') {
            steps {
                script {
                    sh 'python3 lab2/src/model_preprocessing.py'
                }
            }
        }

        stage('Проверка обученной модели на тестовых данных.') {
            steps {
                script {
                    sh 'python3 lab2/src/model_testing.py'
                }
            }
        }

        stage('Finish') {
            steps {
                script {
                    echo 'Работа скриптов завершена успешно'
                }
            }
        }
    }
}